[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
